<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Proforma_details.php');
	include_once(__DIR__ . '/Proforma_details_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Proforma_details');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Proforma_details';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Proforma_details`.`field1`" => "field1",
		"`Proforma_details`.`Address`" => "Address",
		"`Proforma_details`.`Mobile`" => "Mobile",
		"`Proforma_details`.`Email`" => "Email",
		"if(`Proforma_details`.`Date_Of_Birth`,date_format(`Proforma_details`.`Date_Of_Birth`,'%m/%d/%Y'),'')" => "Date_Of_Birth",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => '`Proforma_details`.`Mobile`',
		4 => 4,
		5 => '`Proforma_details`.`Date_Of_Birth`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Proforma_details`.`field1`" => "field1",
		"`Proforma_details`.`Address`" => "Address",
		"`Proforma_details`.`Mobile`" => "Mobile",
		"`Proforma_details`.`Email`" => "Email",
		"if(`Proforma_details`.`Date_Of_Birth`,date_format(`Proforma_details`.`Date_Of_Birth`,'%m/%d/%Y'),'')" => "Date_Of_Birth",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Proforma_details`.`field1`" => "Name",
		"`Proforma_details`.`Address`" => "Address",
		"`Proforma_details`.`Mobile`" => "Mobile",
		"`Proforma_details`.`Email`" => "Email",
		"`Proforma_details`.`Date_Of_Birth`" => "Date Of Birth",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Proforma_details`.`field1`" => "field1",
		"`Proforma_details`.`Address`" => "Address",
		"`Proforma_details`.`Mobile`" => "Mobile",
		"`Proforma_details`.`Email`" => "Email",
		"if(`Proforma_details`.`Date_Of_Birth`,date_format(`Proforma_details`.`Date_Of_Birth`,'%m/%d/%Y'),'')" => "Date_Of_Birth",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Proforma_details` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Proforma_details_view.php';
	$x->RedirectAfterInsert = 'https://pcb.ap.gov.in/UI/Home.aspx';
	$x->TableTitle = 'Person details';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`Proforma_details`.`field1`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Name', 'Address', 'Mobile', 'Email', 'Date Of Birth', ];
	$x->ColFieldName = ['field1', 'Address', 'Mobile', 'Email', 'Date_Of_Birth', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Proforma_details_templateTV.html';
	$x->SelectedTemplate = 'templates/Proforma_details_templateTVS.html';
	$x->TemplateDV = 'templates/Proforma_details_templateDV.html';
	$x->TemplateDVP = 'templates/Proforma_details_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Proforma_details_init
	$render = true;
	if(function_exists('Proforma_details_init')) {
		$args = [];
		$render = Proforma_details_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Proforma_details_header
	$headerCode = '';
	if(function_exists('Proforma_details_header')) {
		$args = [];
		$headerCode = Proforma_details_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Proforma_details_footer
	$footerCode = '';
	if(function_exists('Proforma_details_footer')) {
		$args = [];
		$footerCode = Proforma_details_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
